package dbchubreast_web.entity;
// Generated 25 janv. 2017 16:49:56 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppLog generated by hbm2java
 */
@Entity
@Table(name = "app_log", schema = "db_chu_breast")
public class AppLog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Date lastActivity;
	private String username;
	private String role;
	private String ip;
	private String method;
	private String route;
	private String url;
	private String parameter;
	private String comment;

	public AppLog() {
	}

	public AppLog(Date lastActivity) {
		this.lastActivity = lastActivity;
	}

	public AppLog(Date lastActivity, String username, String role, String ip, String method, String route, String url,
			String parameter, String comment) {
		this.lastActivity = lastActivity;
		this.username = username;
		this.role = role;
		this.ip = ip;
		this.method = method;
		this.route = route;
		this.url = url;
		this.parameter = parameter;
		this.comment = comment;
	}

	@Id

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_activity", unique = true, nullable = false, length = 29)
	public Date getLastActivity() {
		return this.lastActivity;
	}

	public void setLastActivity(Date lastActivity) {
		this.lastActivity = lastActivity;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "role", length = 500)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "ip", length = 500)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "method", length = 20)
	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	@Column(name = "route", length = 500)
	public String getRoute() {
		return this.route;
	}

	public void setRoute(String route) {
		this.route = route;
	}

	@Column(name = "url", length = 500)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "parameter")
	public String getParameter() {
		return this.parameter;
	}

	public void setParameter(String parameter) {
		this.parameter = parameter;
	}

	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((lastActivity == null) ? 0 : lastActivity.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AppLog other = (AppLog) obj;
		if (lastActivity == null) {
			if (other.lastActivity != null)
				return false;
		} else if (!lastActivity.equals(other.lastActivity))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "AppLog [lastActivity=" + lastActivity + ", username=" + username + ", role=" + role + ", ip=" + ip
				+ ", method=" + method + ", route=" + route + ", url=" + url + ", parameter=" + parameter + ", comment="
				+ comment + "]";
	}
	
	

}
