package dbchubreast_web.entity;
// Generated 26 janv. 2017 10:09:25 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * AppRole generated by hbm2java
 */
@Entity
@Table(name = "app_role", schema = "db_chu_breast")
public class AppRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idRole;
	private String name;
	private List<AppUser> appUsers = new ArrayList<AppUser>(0);
	private List<AppMenu> appMenus = new ArrayList<AppMenu>(0);

	public AppRole() {
	}

	public AppRole(String idRole, String name) {
		this.idRole = idRole;
		this.name = name;
	}

	public AppRole(String idRole, String name, List<AppUser> appUsers, List<AppMenu> appMenus) {
		this.idRole = idRole;
		this.name = name;
		this.appUsers = appUsers;
		this.appMenus = appMenus;
	}

	@Id

	@Column(name = "id_role", unique = true, nullable = false, length = 50)
	public String getIdRole() {
		return this.idRole;
	}

	public void setIdRole(String idRole) {
		this.idRole = idRole;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "appRoles")
	public List<AppUser> getAppUsers() {
		return this.appUsers;
	}

	public void setAppUsers(List<AppUser> appUsers) {
		this.appUsers = appUsers;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "app_role_menu", schema = "db_chu_breast", joinColumns = {
			@JoinColumn(name = "id_role", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_menu", nullable = false, updatable = false) })
	public List<AppMenu> getAppMenus() {
		return this.appMenus;
	}

	public void setAppMenus(List<AppMenu> appMenus) {
		this.appMenus = appMenus;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idRole == null) ? 0 : idRole.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AppRole other = (AppRole) obj;
		if (idRole == null) {
			if (other.idRole != null)
				return false;
		} else if (!idRole.equals(other.idRole))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "AppRole [idRole=" + idRole + ", name=" + name + "]";
	}

	
	
}
