package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChuAdresse generated by hbm2java
 */
@Entity
@Table(name = "chu_adresse", schema = "db_chu_breast")
public class ChuAdresse implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idAdresse;
	private ChuCommune chuCommune;
	private ChuPatient chuPatient;
	private ChuTypeAdresse chuTypeAdresse;
	private String duree;
	private String remarque;

	public ChuAdresse() {
	}

	public ChuAdresse(Integer idAdresse, ChuCommune chuCommune, ChuPatient chuPatient, ChuTypeAdresse chuTypeAdresse) {
		this.idAdresse = idAdresse;
		this.chuCommune = chuCommune;
		this.chuPatient = chuPatient;
		this.chuTypeAdresse = chuTypeAdresse;
	}

	public ChuAdresse(Integer idAdresse, ChuCommune chuCommune, ChuPatient chuPatient, ChuTypeAdresse chuTypeAdresse,
			String duree, String remarque) {
		this.idAdresse = idAdresse;
		this.chuCommune = chuCommune;
		this.chuPatient = chuPatient;
		this.chuTypeAdresse = chuTypeAdresse;
		this.duree = duree;
		this.remarque = remarque;
	}

	@Id

	@Column(name = "id_adresse", unique = true, nullable = false)
	public Integer getIdAdresse() {
		return this.idAdresse;
	}

	public void setIdAdresse(Integer idAdresse) {
		this.idAdresse = idAdresse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "insee", nullable = false)
	public ChuCommune getChuCommune() {
		return this.chuCommune;
	}

	public void setChuCommune(ChuCommune chuCommune) {
		this.chuCommune = chuCommune;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_patient", nullable = false)
	public ChuPatient getChuPatient() {
		return this.chuPatient;
	}

	public void setChuPatient(ChuPatient chuPatient) {
		this.chuPatient = chuPatient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_type_adresse", nullable = false)
	public ChuTypeAdresse getChuTypeAdresse() {
		return this.chuTypeAdresse;
	}

	public void setChuTypeAdresse(ChuTypeAdresse chuTypeAdresse) {
		this.chuTypeAdresse = chuTypeAdresse;
	}

	@Column(name = "duree", length = 100)
	public String getDuree() {
		return this.duree;
	}

	public void setDuree(String duree) {
		this.duree = duree;
	}

	@Column(name = "remarque")
	public String getRemarque() {
		return this.remarque;
	}

	public void setRemarque(String remarque) {
		this.remarque = remarque;
	}

}
