package dbchubreast_web.entity;
// Generated 21 d�c. 2016 09:29:09 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChuAntecedentGyneco generated by hbm2java
 */
@Entity
@Table(name = "chu_antecedent_gyneco", schema = "db_chu_breast")
public class ChuAntecedentGyneco implements java.io.Serializable {

	private Integer idAntecedentGyneco;
	private ChuCodeTh chuCodeThByIdContraceptif;
	private ChuCodeTh chuCodeThByIdThs;
	private String pathologie;
	private Integer ageRegles;
	private Integer ageMenopause;
	private Integer nbEnfants;
	private Integer agePremierEnfant;
	private Integer ageDernierEnfant;
	private Integer nbFaussesCouches;
	private String allaitement;
	private Set<ChuPatient> chuPatients = new HashSet<ChuPatient>(0);

	public ChuAntecedentGyneco() {
	}

	public ChuAntecedentGyneco(Integer idAntecedentGyneco) {
		this.idAntecedentGyneco = idAntecedentGyneco;
	}

	public ChuAntecedentGyneco(Integer idAntecedentGyneco, ChuCodeTh chuCodeThByIdContraceptif,
			ChuCodeTh chuCodeThByIdThs, String pathologie, Integer ageRegles, Integer ageMenopause, Integer nbEnfants,
			Integer agePremierEnfant, Integer ageDernierEnfant, Integer nbFaussesCouches, String allaitement,
			Set<ChuPatient> chuPatients) {
		this.idAntecedentGyneco = idAntecedentGyneco;
		this.chuCodeThByIdContraceptif = chuCodeThByIdContraceptif;
		this.chuCodeThByIdThs = chuCodeThByIdThs;
		this.pathologie = pathologie;
		this.ageRegles = ageRegles;
		this.ageMenopause = ageMenopause;
		this.nbEnfants = nbEnfants;
		this.agePremierEnfant = agePremierEnfant;
		this.ageDernierEnfant = ageDernierEnfant;
		this.nbFaussesCouches = nbFaussesCouches;
		this.allaitement = allaitement;
		this.chuPatients = chuPatients;
	}

	@Id

	@Column(name = "id_antecedent_gyneco", unique = true, nullable = false)
	public Integer getIdAntecedentGyneco() {
		return this.idAntecedentGyneco;
	}

	public void setIdAntecedentGyneco(Integer idAntecedentGyneco) {
		this.idAntecedentGyneco = idAntecedentGyneco;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_contraceptif")
	public ChuCodeTh getChuCodeThByIdContraceptif() {
		return this.chuCodeThByIdContraceptif;
	}

	public void setChuCodeThByIdContraceptif(ChuCodeTh chuCodeThByIdContraceptif) {
		this.chuCodeThByIdContraceptif = chuCodeThByIdContraceptif;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ths")
	public ChuCodeTh getChuCodeThByIdThs() {
		return this.chuCodeThByIdThs;
	}

	public void setChuCodeThByIdThs(ChuCodeTh chuCodeThByIdThs) {
		this.chuCodeThByIdThs = chuCodeThByIdThs;
	}

	@Column(name = "pathologie")
	public String getPathologie() {
		return this.pathologie;
	}

	public void setPathologie(String pathologie) {
		this.pathologie = pathologie;
	}

	@Column(name = "age_regles")
	public Integer getAgeRegles() {
		return this.ageRegles;
	}

	public void setAgeRegles(Integer ageRegles) {
		this.ageRegles = ageRegles;
	}

	@Column(name = "age_menopause")
	public Integer getAgeMenopause() {
		return this.ageMenopause;
	}

	public void setAgeMenopause(Integer ageMenopause) {
		this.ageMenopause = ageMenopause;
	}

	@Column(name = "nb_enfants")
	public Integer getNbEnfants() {
		return this.nbEnfants;
	}

	public void setNbEnfants(Integer nbEnfants) {
		this.nbEnfants = nbEnfants;
	}

	@Column(name = "age_premier_enfant")
	public Integer getAgePremierEnfant() {
		return this.agePremierEnfant;
	}

	public void setAgePremierEnfant(Integer agePremierEnfant) {
		this.agePremierEnfant = agePremierEnfant;
	}

	@Column(name = "age_dernier_enfant")
	public Integer getAgeDernierEnfant() {
		return this.ageDernierEnfant;
	}

	public void setAgeDernierEnfant(Integer ageDernierEnfant) {
		this.ageDernierEnfant = ageDernierEnfant;
	}

	@Column(name = "nb_fausses_couches")
	public Integer getNbFaussesCouches() {
		return this.nbFaussesCouches;
	}

	public void setNbFaussesCouches(Integer nbFaussesCouches) {
		this.nbFaussesCouches = nbFaussesCouches;
	}

	@Column(name = "allaitement", length = 100)
	public String getAllaitement() {
		return this.allaitement;
	}

	public void setAllaitement(String allaitement) {
		this.allaitement = allaitement;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuAntecedentGyneco")
	public Set<ChuPatient> getChuPatients() {
		return this.chuPatients;
	}

	public void setChuPatients(Set<ChuPatient> chuPatients) {
		this.chuPatients = chuPatients;
	}

}
