package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChuAntecedentGeneralId generated by hbm2java
 */
@Embeddable
public class ChuAntecedentGeneralId implements java.io.Serializable {

	private String idPatient;
	private String idMaladie;

	public ChuAntecedentGeneralId() {
	}

	public ChuAntecedentGeneralId(String idPatient, String idMaladie) {
		this.idPatient = idPatient;
		this.idMaladie = idMaladie;
	}

	@Column(name = "id_patient", nullable = false, length = 20)
	public String getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(String idPatient) {
		this.idPatient = idPatient;
	}

	@Column(name = "id_maladie", nullable = false, length = 10)
	public String getIdMaladie() {
		return this.idMaladie;
	}

	public void setIdMaladie(String idMaladie) {
		this.idMaladie = idMaladie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChuAntecedentGeneralId))
			return false;
		ChuAntecedentGeneralId castOther = (ChuAntecedentGeneralId) other;

		return ((this.getIdPatient() == castOther.getIdPatient()) || (this.getIdPatient() != null
				&& castOther.getIdPatient() != null && this.getIdPatient().equals(castOther.getIdPatient())))
				&& ((this.getIdMaladie() == castOther.getIdMaladie()) || (this.getIdMaladie() != null
						&& castOther.getIdMaladie() != null && this.getIdMaladie().equals(castOther.getIdMaladie())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdPatient() == null ? 0 : this.getIdPatient().hashCode());
		result = 37 * result + (getIdMaladie() == null ? 0 : this.getIdMaladie().hashCode());
		return result;
	}

}
