package dbchubreast_web.entity;
// Generated 25 janv. 2017 11:16:29 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChuBiomarqueur generated by hbm2java
 */
@Entity
@Table(name = "chu_biomarqueur", schema = "db_chu_breast")
public class ChuBiomarqueur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idBiomarqueur;
	private String nom;
	private Integer ordre;
	private List<ChuPrelevementBiomarqueur> chuPrelevementBiomarqueurs = new ArrayList<ChuPrelevementBiomarqueur>(0);

	public ChuBiomarqueur() {
	}

	public ChuBiomarqueur(String idBiomarqueur, String nom) {
		this.idBiomarqueur = idBiomarqueur;
		this.nom = nom;
	}

	public ChuBiomarqueur(String idBiomarqueur, String nom, Integer ordre,
			List<ChuPrelevementBiomarqueur> chuPrelevementBiomarqueurs) {
		this.idBiomarqueur = idBiomarqueur;
		this.nom = nom;
		this.ordre = ordre;
		this.chuPrelevementBiomarqueurs = chuPrelevementBiomarqueurs;
	}

	@Id

	@Column(name = "id_biomarqueur", unique = true, nullable = false, length = 20)
	public String getIdBiomarqueur() {
		return this.idBiomarqueur;
	}

	public void setIdBiomarqueur(String idBiomarqueur) {
		this.idBiomarqueur = idBiomarqueur;
	}

	@Column(name = "nom", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "ordre")
	public Integer getOrdre() {
		return this.ordre;
	}

	public void setOrdre(Integer ordre) {
		this.ordre = ordre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuBiomarqueur")
	public List<ChuPrelevementBiomarqueur> getChuPrelevementBiomarqueurs() {
		return this.chuPrelevementBiomarqueurs;
	}

	public void setChuPrelevementBiomarqueurs(List<ChuPrelevementBiomarqueur> chuPrelevementBiomarqueurs) {
		this.chuPrelevementBiomarqueurs = chuPrelevementBiomarqueurs;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idBiomarqueur == null) ? 0 : idBiomarqueur.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ChuBiomarqueur other = (ChuBiomarqueur) obj;
		if (idBiomarqueur == null) {
			if (other.idBiomarqueur != null)
				return false;
		} else if (!idBiomarqueur.equals(other.idBiomarqueur))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ChuBiomarqueur [idBiomarqueur=" + idBiomarqueur + ", nom=" + nom + ", ordre=" + ordre + "]";
	}
	
	

}
