package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChuCommune generated by hbm2java
 */
@Entity
@Table(name = "chu_commune", schema = "db_chu_breast")
public class ChuCommune implements java.io.Serializable {

	private String insee;
	private String codePostal;
	private String nom;
	private Set<ChuAdresse> chuAdresses = new HashSet<ChuAdresse>(0);

	public ChuCommune() {
	}

	public ChuCommune(String insee, String codePostal, String nom) {
		this.insee = insee;
		this.codePostal = codePostal;
		this.nom = nom;
	}

	public ChuCommune(String insee, String codePostal, String nom, Set<ChuAdresse> chuAdresses) {
		this.insee = insee;
		this.codePostal = codePostal;
		this.nom = nom;
		this.chuAdresses = chuAdresses;
	}

	@Id

	@Column(name = "insee", unique = true, nullable = false, length = 5)
	public String getInsee() {
		return this.insee;
	}

	public void setInsee(String insee) {
		this.insee = insee;
	}

	@Column(name = "code_postal", nullable = false, length = 5)
	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	@Column(name = "nom", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuCommune")
	public Set<ChuAdresse> getChuAdresses() {
		return this.chuAdresses;
	}

	public void setChuAdresses(Set<ChuAdresse> chuAdresses) {
		this.chuAdresses = chuAdresses;
	}

}
