package dbchubreast_web.entity;
// Generated 12 mai 2017 13:31:51 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * ChuComposantTraitement generated by hbm2java
 */
@Entity
@Table(name = "chu_composant_traitement", schema = "db_chu_breast")
public class ChuComposantTraitement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idComposant;
	private ChuMethodeTraitement chuMethodeTraitement;
	private String nomInternational;
	private String nomCommercial;
	private String classe;
	private String action;
	private List<ChuProtocoleTraitement> chuProtocoleTraitements = new ArrayList<ChuProtocoleTraitement>(0);

	public ChuComposantTraitement() {
	}

	public ChuComposantTraitement(Integer idComposant, ChuMethodeTraitement chuMethodeTraitement,
			String nomInternational) {
		this.idComposant = idComposant;
		this.chuMethodeTraitement = chuMethodeTraitement;
		this.nomInternational = nomInternational;
	}

	public ChuComposantTraitement(Integer idComposant, ChuMethodeTraitement chuMethodeTraitement,
			String nomInternational, String nomCommercial, String classe, String action,
			List<ChuProtocoleTraitement> chuProtocoleTraitements) {
		this.idComposant = idComposant;
		this.chuMethodeTraitement = chuMethodeTraitement;
		this.nomInternational = nomInternational;
		this.nomCommercial = nomCommercial;
		this.classe = classe;
		this.action = action;
		this.chuProtocoleTraitements = chuProtocoleTraitements;
	}

	@Id
	@GeneratedValue(generator = "increment")
	@GenericGenerator(name = "increment", strategy = "increment")
	@Column(name = "id_composant", unique = true, nullable = false)
	public Integer getIdComposant() {
		return this.idComposant;
	}

	public void setIdComposant(Integer idComposant) {
		this.idComposant = idComposant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_methode", nullable = false)
	public ChuMethodeTraitement getChuMethodeTraitement() {
		return this.chuMethodeTraitement;
	}

	public void setChuMethodeTraitement(ChuMethodeTraitement chuMethodeTraitement) {
		this.chuMethodeTraitement = chuMethodeTraitement;
	}

	@Column(name = "nom_international", nullable = false, length = 500)
	public String getNomInternational() {
		return this.nomInternational;
	}

	public void setNomInternational(String nomInternational) {
		this.nomInternational = nomInternational;
	}

	@Column(name = "nom_commercial", length = 500)
	public String getNomCommercial() {
		return this.nomCommercial;
	}

	public void setNomCommercial(String nomCommercial) {
		this.nomCommercial = nomCommercial;
	}

	@Column(name = "classe", length = 500)
	public String getClasse() {
		return this.classe;
	}

	public void setClasse(String classe) {
		this.classe = classe;
	}

	@Column(name = "action", length = 500)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "chuComposantTraitements")
	public List<ChuProtocoleTraitement> getChuProtocoleTraitements() {
		return this.chuProtocoleTraitements;
	}

	public void setChuProtocoleTraitements(List<ChuProtocoleTraitement> chuProtocoleTraitements) {
		this.chuProtocoleTraitements = chuProtocoleTraitements;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idComposant == null) ? 0 : idComposant.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ChuComposantTraitement other = (ChuComposantTraitement) obj;
		if (idComposant == null) {
			if (other.idComposant != null)
				return false;
		} else if (!idComposant.equals(other.idComposant))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ChuComposantTraitement [idComposant=" + idComposant + ", nomInternational=" + nomInternational
				+ ", nomCommercial=" + nomCommercial + ", classe=" + classe + ", action=" + action + "]";
	}

}
