package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChuEvolution generated by hbm2java
 */
@Entity
@Table(name = "chu_evolution", schema = "db_chu_breast")
public class ChuEvolution implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idEvolution;
	private String code;
	private String nom;
	private List<ChuTumeur> chuTumeurs = new ArrayList<ChuTumeur>(0);

	public ChuEvolution() {
	}

	public ChuEvolution(Integer idEvolution, String nom) {
		this.idEvolution = idEvolution;
		this.nom = nom;
	}
	
	

	/**
	 * @param idEvolution
	 * @param code
	 * @param nom
	 */
	public ChuEvolution(Integer idEvolution, String code, String nom) {
		super();
		this.idEvolution = idEvolution;
		this.code = code;
		this.nom = nom;
	}

	public ChuEvolution(Integer idEvolution, String code, String nom, List<ChuTumeur> chuTumeurs) {
		this.idEvolution = idEvolution;
		this.code = code;
		this.nom = nom;
		this.chuTumeurs = chuTumeurs;
	}

	@Id

	@Column(name = "id_evolution", unique = true, nullable = false)
	public Integer getIdEvolution() {
		return this.idEvolution;
	}

	public void setIdEvolution(Integer idEvolution) {
		this.idEvolution = idEvolution;
	}

	@Column(name = "code", length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "nom", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuEvolution")
	public List<ChuTumeur> getChuTumeurs() {
		return this.chuTumeurs;
	}

	public void setChuTumeurs(List<ChuTumeur> chuTumeurs) {
		this.chuTumeurs = chuTumeurs;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idEvolution == null) ? 0 : idEvolution.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ChuEvolution other = (ChuEvolution) obj;
		if (idEvolution == null) {
			if (other.idEvolution != null)
				return false;
		} else if (!idEvolution.equals(other.idEvolution))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ChuEvolution [idEvolution=" + idEvolution + ", code=" + code + ", nom=" + nom + "]";
	}
	
	

}
