package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChuGroupeTopographie generated by hbm2java
 */
@Entity
@Table(name = "chu_groupe_topographie", schema = "db_chu_breast")
public class ChuGroupeTopographie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idGroupeTopo;
	private String nom;
	private List<ChuTopographie> chuTopographies = new ArrayList<ChuTopographie>(0);

	public ChuGroupeTopographie() {
	}

	public ChuGroupeTopographie(String idGroupeTopo, String nom) {
		this.idGroupeTopo = idGroupeTopo;
		this.nom = nom;
	}

	public ChuGroupeTopographie(String idGroupeTopo, String nom, List<ChuTopographie> chuTopographies) {
		this.idGroupeTopo = idGroupeTopo;
		this.nom = nom;
		this.chuTopographies = chuTopographies;
	}

	@Id

	@Column(name = "id_groupe_topo", unique = true, nullable = false, length = 20)
	public String getIdGroupeTopo() {
		return this.idGroupeTopo;
	}

	public void setIdGroupeTopo(String idGroupeTopo) {
		this.idGroupeTopo = idGroupeTopo;
	}

	@Column(name = "nom", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuGroupeTopographie")
	public List<ChuTopographie> getChuTopographies() {
		return this.chuTopographies;
	}

	public void setChuTopographies(List<ChuTopographie> chuTopographies) {
		this.chuTopographies = chuTopographies;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idGroupeTopo == null) ? 0 : idGroupeTopo.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ChuGroupeTopographie other = (ChuGroupeTopographie) obj;
		if (idGroupeTopo == null) {
			if (other.idGroupeTopo != null)
				return false;
		} else if (!idGroupeTopo.equals(other.idGroupeTopo))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ChuGroupeTopographie [idGroupeTopo=" + idGroupeTopo + ", nom=" + nom + "]";
	}

}
