package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChuGroupeMaladie generated by hbm2java
 */
@Entity
@Table(name = "chu_groupe_maladie", schema = "db_chu_breast")
public class ChuGroupeMaladie implements java.io.Serializable {

	private Integer idGroupeMaladie;
	private String nomGroupe;
	private String remarque;
	private Set<ChuMaladie> chuMaladies = new HashSet<ChuMaladie>(0);
	private Set<ChuAntecedentGeneral> chuAntecedentGenerals = new HashSet<ChuAntecedentGeneral>(0);

	public ChuGroupeMaladie() {
	}

	public ChuGroupeMaladie(Integer idGroupeMaladie, String nomGroupe) {
		this.idGroupeMaladie = idGroupeMaladie;
		this.nomGroupe = nomGroupe;
	}

	public ChuGroupeMaladie(Integer idGroupeMaladie, String nomGroupe, String remarque, Set<ChuMaladie> chuMaladies,
			Set<ChuAntecedentGeneral> chuAntecedentGenerals) {
		this.idGroupeMaladie = idGroupeMaladie;
		this.nomGroupe = nomGroupe;
		this.remarque = remarque;
		this.chuMaladies = chuMaladies;
		this.chuAntecedentGenerals = chuAntecedentGenerals;
	}

	@Id

	@Column(name = "id_groupe_maladie", unique = true, nullable = false)
	public Integer getIdGroupeMaladie() {
		return this.idGroupeMaladie;
	}

	public void setIdGroupeMaladie(Integer idGroupeMaladie) {
		this.idGroupeMaladie = idGroupeMaladie;
	}

	@Column(name = "nom_groupe", nullable = false)
	public String getNomGroupe() {
		return this.nomGroupe;
	}

	public void setNomGroupe(String nomGroupe) {
		this.nomGroupe = nomGroupe;
	}

	@Column(name = "remarque", length = 500)
	public String getRemarque() {
		return this.remarque;
	}

	public void setRemarque(String remarque) {
		this.remarque = remarque;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuGroupeMaladie")
	public Set<ChuMaladie> getChuMaladies() {
		return this.chuMaladies;
	}

	public void setChuMaladies(Set<ChuMaladie> chuMaladies) {
		this.chuMaladies = chuMaladies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuGroupeMaladie")
	public Set<ChuAntecedentGeneral> getChuAntecedentGenerals() {
		return this.chuAntecedentGenerals;
	}

	public void setChuAntecedentGenerals(Set<ChuAntecedentGeneral> chuAntecedentGenerals) {
		this.chuAntecedentGenerals = chuAntecedentGenerals;
	}

}
