package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChuMorphologie generated by hbm2java
 */
@Entity
@Table(name = "chu_morphologie", schema = "db_chu_breast")
public class ChuMorphologie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idMorphologie;
	private String nomFr;
	private String nomEn;
	private List<ChuPrelevement> chuPrelevements = new ArrayList<ChuPrelevement>(0);

	public ChuMorphologie() {
	}

	public ChuMorphologie(String idMorphologie) {
		this.idMorphologie = idMorphologie;
	}

	public ChuMorphologie(String idMorphologie, String nomFr, String nomEn, List<ChuPrelevement> chuPrelevements) {
		this.idMorphologie = idMorphologie;
		this.nomFr = nomFr;
		this.nomEn = nomEn;
		this.chuPrelevements = chuPrelevements;
	}

	@Id

	@Column(name = "id_morphologie", unique = true, nullable = false, length = 20)
	public String getIdMorphologie() {
		return this.idMorphologie;
	}

	public void setIdMorphologie(String idMorphologie) {
		this.idMorphologie = idMorphologie;
	}

	@Column(name = "nom_fr")
	public String getNomFr() {
		return this.nomFr;
	}

	public void setNomFr(String nomFr) {
		this.nomFr = nomFr;
	}

	@Column(name = "nom_en")
	public String getNomEn() {
		return this.nomEn;
	}

	public void setNomEn(String nomEn) {
		this.nomEn = nomEn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuMorphologie")
	public List<ChuPrelevement> getChuPrelevements() {
		return this.chuPrelevements;
	}

	public void setChuPrelevements(List<ChuPrelevement> chuPrelevements) {
		this.chuPrelevements = chuPrelevements;
	}

	@Override
	public String toString() {
		return "ChuMorphologie [idMorphologie=" + idMorphologie + ", nomFr=" + nomFr + ", nomEn=" + nomEn + "]";
	}
	
	

}
