package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChuModeVie generated by hbm2java
 */
@Entity
@Table(name = "chu_mode_vie", schema = "db_chu_breast")
public class ChuModeVie implements java.io.Serializable {

	private Integer idModeVie;
	private String activitePhysique;
	private String cosmetique;
	private String bricolage;
	private String exposition;
	private String tabacStatut;
	private String tabacPan;
	private String alcool;
	private String drogue;
	private String travailDeNuit;
	private String autre;
	private Set<ChuPatient> chuPatients = new HashSet<ChuPatient>(0);

	public ChuModeVie() {
	}

	public ChuModeVie(Integer idModeVie) {
		this.idModeVie = idModeVie;
	}

	public ChuModeVie(Integer idModeVie, String activitePhysique, String cosmetique, String bricolage,
			String exposition, String tabacStatut, String tabacPan, String alcool, String drogue, String travailDeNuit,
			String autre, Set<ChuPatient> chuPatients) {
		this.idModeVie = idModeVie;
		this.activitePhysique = activitePhysique;
		this.cosmetique = cosmetique;
		this.bricolage = bricolage;
		this.exposition = exposition;
		this.tabacStatut = tabacStatut;
		this.tabacPan = tabacPan;
		this.alcool = alcool;
		this.drogue = drogue;
		this.travailDeNuit = travailDeNuit;
		this.autre = autre;
		this.chuPatients = chuPatients;
	}

	@Id

	@Column(name = "id_mode_vie", unique = true, nullable = false)
	public Integer getIdModeVie() {
		return this.idModeVie;
	}

	public void setIdModeVie(Integer idModeVie) {
		this.idModeVie = idModeVie;
	}

	@Column(name = "activite_physique")
	public String getActivitePhysique() {
		return this.activitePhysique;
	}

	public void setActivitePhysique(String activitePhysique) {
		this.activitePhysique = activitePhysique;
	}

	@Column(name = "cosmetique", length = 100)
	public String getCosmetique() {
		return this.cosmetique;
	}

	public void setCosmetique(String cosmetique) {
		this.cosmetique = cosmetique;
	}

	@Column(name = "bricolage", length = 100)
	public String getBricolage() {
		return this.bricolage;
	}

	public void setBricolage(String bricolage) {
		this.bricolage = bricolage;
	}

	@Column(name = "exposition")
	public String getExposition() {
		return this.exposition;
	}

	public void setExposition(String exposition) {
		this.exposition = exposition;
	}

	@Column(name = "tabac_statut", length = 100)
	public String getTabacStatut() {
		return this.tabacStatut;
	}

	public void setTabacStatut(String tabacStatut) {
		this.tabacStatut = tabacStatut;
	}

	@Column(name = "tabac_pan", length = 100)
	public String getTabacPan() {
		return this.tabacPan;
	}

	public void setTabacPan(String tabacPan) {
		this.tabacPan = tabacPan;
	}

	@Column(name = "alcool")
	public String getAlcool() {
		return this.alcool;
	}

	public void setAlcool(String alcool) {
		this.alcool = alcool;
	}

	@Column(name = "drogue")
	public String getDrogue() {
		return this.drogue;
	}

	public void setDrogue(String drogue) {
		this.drogue = drogue;
	}

	@Column(name = "travail_de_nuit", length = 100)
	public String getTravailDeNuit() {
		return this.travailDeNuit;
	}

	public void setTravailDeNuit(String travailDeNuit) {
		this.travailDeNuit = travailDeNuit;
	}

	@Column(name = "autre")
	public String getAutre() {
		return this.autre;
	}

	public void setAutre(String autre) {
		this.autre = autre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuModeVie")
	public Set<ChuPatient> getChuPatients() {
		return this.chuPatients;
	}

	public void setChuPatients(Set<ChuPatient> chuPatients) {
		this.chuPatients = chuPatients;
	}

}
