package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChuMaladie generated by hbm2java
 */
@Entity
@Table(name = "chu_maladie", schema = "db_chu_breast")
public class ChuMaladie implements java.io.Serializable {

	private String idMaladie;
	private ChuGroupeMaladie chuGroupeMaladie;
	private String nom;
	private Integer scoreCharlson;
	private Set<ChuAntecedentGeneral> chuAntecedentGenerals = new HashSet<ChuAntecedentGeneral>(0);

	public ChuMaladie() {
	}

	public ChuMaladie(String idMaladie, String nom, Integer scoreCharlson) {
		this.idMaladie = idMaladie;
		this.nom = nom;
		this.scoreCharlson = scoreCharlson;
	}

	public ChuMaladie(String idMaladie, ChuGroupeMaladie chuGroupeMaladie, String nom, Integer scoreCharlson,
			Set<ChuAntecedentGeneral> chuAntecedentGenerals) {
		this.idMaladie = idMaladie;
		this.chuGroupeMaladie = chuGroupeMaladie;
		this.nom = nom;
		this.scoreCharlson = scoreCharlson;
		this.chuAntecedentGenerals = chuAntecedentGenerals;
	}

	@Id

	@Column(name = "id_maladie", unique = true, nullable = false, length = 10)
	public String getIdMaladie() {
		return this.idMaladie;
	}

	public void setIdMaladie(String idMaladie) {
		this.idMaladie = idMaladie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_groupe_maladie")
	public ChuGroupeMaladie getChuGroupeMaladie() {
		return this.chuGroupeMaladie;
	}

	public void setChuGroupeMaladie(ChuGroupeMaladie chuGroupeMaladie) {
		this.chuGroupeMaladie = chuGroupeMaladie;
	}

	@Column(name = "nom", nullable = false, length = 500)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "score_charlson", nullable = false)
	public Integer getScoreCharlson() {
		return this.scoreCharlson;
	}

	public void setScoreCharlson(Integer scoreCharlson) {
		this.scoreCharlson = scoreCharlson;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuMaladie")
	public Set<ChuAntecedentGeneral> getChuAntecedentGenerals() {
		return this.chuAntecedentGenerals;
	}

	public void setChuAntecedentGenerals(Set<ChuAntecedentGeneral> chuAntecedentGenerals) {
		this.chuAntecedentGenerals = chuAntecedentGenerals;
	}

}
