package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChuPrelevementBiomarqueur generated by hbm2java
 */
@Entity
@Table(name = "chu_prelevement_biomarqueur", schema = "db_chu_breast")
public class ChuPrelevementBiomarqueur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ChuPrelevementBiomarqueurId id;
	private ChuBiomarqueur chuBiomarqueur;
	private ChuPrelevement chuPrelevement;
	private String valeur;
	private String statut;

	public ChuPrelevementBiomarqueur() {
	}

	public ChuPrelevementBiomarqueur(ChuPrelevementBiomarqueurId id, ChuBiomarqueur chuBiomarqueur,
			ChuPrelevement chuPrelevement) {
		this.id = id;
		this.chuBiomarqueur = chuBiomarqueur;
		this.chuPrelevement = chuPrelevement;
	}

	public ChuPrelevementBiomarqueur(ChuPrelevementBiomarqueurId id, ChuBiomarqueur chuBiomarqueur,
			ChuPrelevement chuPrelevement, String valeur, String statut) {
		this.id = id;
		this.chuBiomarqueur = chuBiomarqueur;
		this.chuPrelevement = chuPrelevement;
		this.valeur = valeur;
		this.statut = statut;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idPrelevement", column = @Column(name = "id_prelevement", nullable = false)),
			@AttributeOverride(name = "idBiomarqueur", column = @Column(name = "id_biomarqueur", nullable = false, length = 20)) })
	public ChuPrelevementBiomarqueurId getId() {
		return this.id;
	}

	public void setId(ChuPrelevementBiomarqueurId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_biomarqueur", nullable = false, insertable = false, updatable = false)
	public ChuBiomarqueur getChuBiomarqueur() {
		return this.chuBiomarqueur;
	}

	public void setChuBiomarqueur(ChuBiomarqueur chuBiomarqueur) {
		this.chuBiomarqueur = chuBiomarqueur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prelevement", nullable = false, insertable = false, updatable = false)
	public ChuPrelevement getChuPrelevement() {
		return this.chuPrelevement;
	}

	public void setChuPrelevement(ChuPrelevement chuPrelevement) {
		this.chuPrelevement = chuPrelevement;
	}

	@Column(name = "valeur", length = 100)
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

	@Column(name = "statut", length = 100)
	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ChuPrelevementBiomarqueur other = (ChuPrelevementBiomarqueur) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ChuPrelevementBiomarqueur [id=" + id + ", valeur=" + valeur + ", statut=" + statut + "]";
	}

}
