package dbchubreast_web.entity;
// Generated 16 mai 2018 12:50:32 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChuPatientParameter generated by hbm2java
 */
@Entity
@Table(name = "chu_patient_parameter")
public class ChuPatientParameter implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
	private ChuPatientParameterId id;
	private ChuParameter chuParameter;
	private ChuPatient chuPatient;
	private String valeur;
	private Date dateImport;
	private boolean enabled;

	public ChuPatientParameter() {
	}

	public ChuPatientParameter(ChuPatientParameterId id, ChuParameter chuParameter, ChuPatient chuPatient,
			String valeur, Date dateImport, boolean enabled) {
		this.id = id;
		this.chuParameter = chuParameter;
		this.chuPatient = chuPatient;
		this.valeur = valeur;
		this.dateImport = dateImport;
		this.enabled = enabled;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idPatient", column = @Column(name = "id_patient", nullable = false, length = 20)),
			@AttributeOverride(name = "idParameter", column = @Column(name = "id_parameter", nullable = false)) })
	public ChuPatientParameterId getId() {
		return this.id;
	}

	public void setId(ChuPatientParameterId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_parameter", nullable = false, insertable = false, updatable = false)
	public ChuParameter getChuParameter() {
		return this.chuParameter;
	}

	public void setChuParameter(ChuParameter chuParameter) {
		this.chuParameter = chuParameter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_patient", nullable = false, insertable = false, updatable = false)
	public ChuPatient getChuPatient() {
		return this.chuPatient;
	}

	public void setChuPatient(ChuPatient chuPatient) {
		this.chuPatient = chuPatient;
	}

	@Column(name = "valeur", nullable = false)
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_import", nullable = false, length = 13)
	public Date getDateImport() {
		return this.dateImport;
	}

	public void setDateImport(Date dateImport) {
		this.dateImport = dateImport;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ChuPatientParameter other = (ChuPatientParameter) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ChuPatientParameter [id=" + id + ", valeur=" + valeur + ", dateImport=" + dateImport + ", enabled="
				+ enabled + "]";
	}

	
	
}
