package dbchubreast_web.entity;
// Generated 16 mai 2018 12:50:32 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChuPatientParameterId generated by hbm2java
 */
@Embeddable
public class ChuPatientParameterId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String idPatient;
	private Integer idParameter;

	public ChuPatientParameterId() {
	}

	public ChuPatientParameterId(String idPatient, Integer idParameter) {
		this.idPatient = idPatient;
		this.idParameter = idParameter;
	}

	@Column(name = "id_patient", nullable = false, length = 20)
	public String getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(String idPatient) {
		this.idPatient = idPatient;
	}

	@Column(name = "id_parameter", nullable = false)
	public Integer getIdParameter() {
		return this.idParameter;
	}

	public void setIdParameter(Integer idParameter) {
		this.idParameter = idParameter;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChuPatientParameterId))
			return false;
		ChuPatientParameterId castOther = (ChuPatientParameterId) other;

		return ((this.getIdPatient() == castOther.getIdPatient()) || (this.getIdPatient() != null
				&& castOther.getIdPatient() != null && this.getIdPatient().equals(castOther.getIdPatient())))
				&& ((this.getIdParameter() == castOther.getIdParameter())
						|| (this.getIdParameter() != null && castOther.getIdParameter() != null
								&& this.getIdParameter().equals(castOther.getIdParameter())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdPatient() == null ? 0 : this.getIdPatient().hashCode());
		result = 37 * result + (getIdParameter() == null ? 0 : this.getIdParameter().hashCode());
		return result;
	}


	public String toString() {
		return "ChuPatientParameterId [idPatient=" + idPatient + ", idParameter=" + idParameter + "]";
	}
	
	

}