package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChuPrelevementBiomarqueurId generated by hbm2java
 */
@Embeddable
public class ChuPrelevementBiomarqueurId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPrelevement;
	private String idBiomarqueur;

	public ChuPrelevementBiomarqueurId() {
	}

	public ChuPrelevementBiomarqueurId(Integer idPrelevement, String idBiomarqueur) {
		this.idPrelevement = idPrelevement;
		this.idBiomarqueur = idBiomarqueur;
	}

	@Column(name = "id_prelevement", nullable = false)
	public Integer getIdPrelevement() {
		return this.idPrelevement;
	}

	public void setIdPrelevement(Integer idPrelevement) {
		this.idPrelevement = idPrelevement;
	}

	@Column(name = "id_biomarqueur", nullable = false, length = 20)
	public String getIdBiomarqueur() {
		return this.idBiomarqueur;
	}

	public void setIdBiomarqueur(String idBiomarqueur) {
		this.idBiomarqueur = idBiomarqueur;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChuPrelevementBiomarqueurId))
			return false;
		ChuPrelevementBiomarqueurId castOther = (ChuPrelevementBiomarqueurId) other;

		return ((this.getIdPrelevement() == castOther.getIdPrelevement())
				|| (this.getIdPrelevement() != null && castOther.getIdPrelevement() != null
						&& this.getIdPrelevement().equals(castOther.getIdPrelevement())))
				&& ((this.getIdBiomarqueur() == castOther.getIdBiomarqueur())
						|| (this.getIdBiomarqueur() != null && castOther.getIdBiomarqueur() != null
								&& this.getIdBiomarqueur().equals(castOther.getIdBiomarqueur())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdPrelevement() == null ? 0 : this.getIdPrelevement().hashCode());
		result = 37 * result + (getIdBiomarqueur() == null ? 0 : this.getIdBiomarqueur().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "ChuPrelevementBiomarqueurId [idPrelevement=" + idPrelevement + ", idBiomarqueur=" + idBiomarqueur + "]";
	}
	
	

}
