package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChuProfession generated by hbm2java
 */
@Entity
@Table(name = "chu_profession", schema = "db_chu_breast")
public class ChuProfession implements java.io.Serializable {

	private Integer idProfession;
	private String nom;
	private Set<ChuPatient> chuPatients = new HashSet<ChuPatient>(0);

	public ChuProfession() {
	}

	public ChuProfession(Integer idProfession, String nom) {
		this.idProfession = idProfession;
		this.nom = nom;
	}

	public ChuProfession(Integer idProfession, String nom, Set<ChuPatient> chuPatients) {
		this.idProfession = idProfession;
		this.nom = nom;
		this.chuPatients = chuPatients;
	}

	@Id

	@Column(name = "id_profession", unique = true, nullable = false)
	public Integer getIdProfession() {
		return this.idProfession;
	}

	public void setIdProfession(Integer idProfession) {
		this.idProfession = idProfession;
	}

	@Column(name = "nom", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuProfession")
	public Set<ChuPatient> getChuPatients() {
		return this.chuPatients;
	}

	public void setChuPatients(Set<ChuPatient> chuPatients) {
		this.chuPatients = chuPatients;
	}

}
