package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChuReponse generated by hbm2java
 */
@Entity
@Table(name = "chu_reponse", schema = "db_chu_breast")
public class ChuReponse implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idReponse;
	private String nom;
	private List<ChuTraitement> chuTraitements = new ArrayList<ChuTraitement>(0);

	public ChuReponse() {
	}

	public ChuReponse(Integer idReponse, String nom) {
		this.idReponse = idReponse;
		this.nom = nom;
	}

	public ChuReponse(Integer idReponse, String nom, List<ChuTraitement> chuTraitements) {
		this.idReponse = idReponse;
		this.nom = nom;
		this.chuTraitements = chuTraitements;
	}

	@Id

	@Column(name = "id_reponse", unique = true, nullable = false)
	public Integer getIdReponse() {
		return this.idReponse;
	}

	public void setIdReponse(Integer idReponse) {
		this.idReponse = idReponse;
	}

	@Column(name = "nom", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuReponse")
	public List<ChuTraitement> getChuTraitements() {
		return this.chuTraitements;
	}

	public void setChuTraitements(List<ChuTraitement> chuTraitements) {
		this.chuTraitements = chuTraitements;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idReponse == null) ? 0 : idReponse.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ChuReponse other = (ChuReponse) obj;
		if (idReponse == null) {
			if (other.idReponse != null)
				return false;
		} else if (!idReponse.equals(other.idReponse))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ChuReponse [idReponse=" + idReponse + ", nom=" + nom + "]";
	}
	
	

}
