package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChuRessourceBiologique generated by hbm2java
 */
@Entity
@Table(name = "chu_ressource_biologique", schema = "db_chu_breast")
public class ChuRessourceBiologique implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idRessource;
	private ChuPrelevement chuPrelevement;
	private String type;
	private String tumoroteque;
	private String clinatec;
	private String adnCirculant;
	private Integer tempsCongelation;
	private Boolean controleHe;

	public ChuRessourceBiologique() {
	}

	public ChuRessourceBiologique(Integer idRessource, ChuPrelevement chuPrelevement) {
		this.idRessource = idRessource;
		this.chuPrelevement = chuPrelevement;
	}

	public ChuRessourceBiologique(Integer idRessource, ChuPrelevement chuPrelevement, String type, String tumoroteque,
			String clinatec, String adnCirculant, Integer tempsCongelation, Boolean controleHe) {
		this.idRessource = idRessource;
		this.chuPrelevement = chuPrelevement;
		this.type = type;
		this.tumoroteque = tumoroteque;
		this.clinatec = clinatec;
		this.adnCirculant = adnCirculant;
		this.tempsCongelation = tempsCongelation;
		this.controleHe = controleHe;
	}

	@Id

	@Column(name = "id_ressource", unique = true, nullable = false)
	public Integer getIdRessource() {
		return this.idRessource;
	}

	public void setIdRessource(Integer idRessource) {
		this.idRessource = idRessource;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prelevement", nullable = false)
	public ChuPrelevement getChuPrelevement() {
		return this.chuPrelevement;
	}

	public void setChuPrelevement(ChuPrelevement chuPrelevement) {
		this.chuPrelevement = chuPrelevement;
	}

	@Column(name = "type", length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "tumoroteque", length = 100)
	public String getTumoroteque() {
		return this.tumoroteque;
	}

	public void setTumoroteque(String tumoroteque) {
		this.tumoroteque = tumoroteque;
	}

	@Column(name = "clinatec", length = 100)
	public String getClinatec() {
		return this.clinatec;
	}

	public void setClinatec(String clinatec) {
		this.clinatec = clinatec;
	}

	@Column(name = "adn_circulant", length = 100)
	public String getAdnCirculant() {
		return this.adnCirculant;
	}

	public void setAdnCirculant(String adnCirculant) {
		this.adnCirculant = adnCirculant;
	}

	@Column(name = "temps_congelation")
	public Integer getTempsCongelation() {
		return this.tempsCongelation;
	}

	public void setTempsCongelation(Integer tempsCongelation) {
		this.tempsCongelation = tempsCongelation;
	}

	@Column(name = "controle_he")
	public Boolean getControleHe() {
		return this.controleHe;
	}

	public void setControleHe(Boolean controleHe) {
		this.controleHe = controleHe;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idRessource == null) ? 0 : idRessource.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ChuRessourceBiologique other = (ChuRessourceBiologique) obj;
		if (idRessource == null) {
			if (other.idRessource != null)
				return false;
		} else if (!idRessource.equals(other.idRessource))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ChuRessourceBiologique [idRessource=" + idRessource + ", type=" + type + ", tumoroteque=" + tumoroteque
				+ ", clinatec=" + clinatec + ", adnCirculant=" + adnCirculant + ", tempsCongelation=" + tempsCongelation
				+ ", controleHe=" + controleHe + "]";
	}

}
