package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChuStatutMarital generated by hbm2java
 */
@Entity
@Table(name = "chu_statut_marital", schema = "db_chu_breast")
public class ChuStatutMarital implements java.io.Serializable {

	private Integer idStatutMarital;
	private String nom;
	private Set<ChuPatient> chuPatients = new HashSet<ChuPatient>(0);

	public ChuStatutMarital() {
	}

	public ChuStatutMarital(Integer idStatutMarital, String nom) {
		this.idStatutMarital = idStatutMarital;
		this.nom = nom;
	}

	public ChuStatutMarital(Integer idStatutMarital, String nom, Set<ChuPatient> chuPatients) {
		this.idStatutMarital = idStatutMarital;
		this.nom = nom;
		this.chuPatients = chuPatients;
	}

	@Id

	@Column(name = "id_statut_marital", unique = true, nullable = false)
	public Integer getIdStatutMarital() {
		return this.idStatutMarital;
	}

	public void setIdStatutMarital(Integer idStatutMarital) {
		this.idStatutMarital = idStatutMarital;
	}

	@Column(name = "nom", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuStatutMarital")
	public Set<ChuPatient> getChuPatients() {
		return this.chuPatients;
	}

	public void setChuPatients(Set<ChuPatient> chuPatients) {
		this.chuPatients = chuPatients;
	}

}
