package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChuTypePrelevement generated by hbm2java
 */
@Entity
@Table(name = "chu_type_prelevement", schema = "db_chu_breast")
public class ChuTypePrelevement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTypePrelevement;
	private String nom;
	private List<ChuPrelevement> chuPrelevements = new ArrayList<ChuPrelevement>(0);

	public ChuTypePrelevement() {
	}

	public ChuTypePrelevement(Integer idTypePrelevement, String nom) {
		this.idTypePrelevement = idTypePrelevement;
		this.nom = nom;
	}

	public ChuTypePrelevement(Integer idTypePrelevement, String nom, List<ChuPrelevement> chuPrelevements) {
		this.idTypePrelevement = idTypePrelevement;
		this.nom = nom;
		this.chuPrelevements = chuPrelevements;
	}

	@Id

	@Column(name = "id_type_prelevement", unique = true, nullable = false)
	public Integer getIdTypePrelevement() {
		return this.idTypePrelevement;
	}

	public void setIdTypePrelevement(Integer idTypePrelevement) {
		this.idTypePrelevement = idTypePrelevement;
	}

	@Column(name = "nom", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuTypePrelevement")
	public List<ChuPrelevement> getChuPrelevements() {
		return this.chuPrelevements;
	}

	public void setChuPrelevements(List<ChuPrelevement> chuPrelevements) {
		this.chuPrelevements = chuPrelevements;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idTypePrelevement == null) ? 0 : idTypePrelevement.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ChuTypePrelevement other = (ChuTypePrelevement) obj;
		if (idTypePrelevement == null) {
			if (other.idTypePrelevement != null)
				return false;
		} else if (!idTypePrelevement.equals(other.idTypePrelevement))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ChuTypePrelevement [idTypePrelevement=" + idTypePrelevement + ", nom=" + nom + "]";
	}
	
	

}
