package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * ChuTnm generated by hbm2java
 */
@Entity
@Table(name = "chu_tnm", schema = "db_chu_breast")
public class ChuTnm implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTnm;
	private ChuPhaseTumeur chuPhaseTumeur;
	private String t;
	private String n;
	private String m;
	private String type;
	private String taille;

	public ChuTnm() {
	}

	public ChuTnm(Integer idTnm, ChuPhaseTumeur chuPhaseTumeur) {
		this.idTnm = idTnm;
		this.chuPhaseTumeur = chuPhaseTumeur;
	}

	public ChuTnm(Integer idTnm, ChuPhaseTumeur chuPhaseTumeur, String t, String n, String m, String type,
			String taille) {
		this.idTnm = idTnm;
		this.chuPhaseTumeur = chuPhaseTumeur;
		this.t = t;
		this.n = n;
		this.m = m;
		this.type = type;
		this.taille = taille;
	}

	@Id
	@GeneratedValue(generator = "increment")
	@GenericGenerator(name = "increment", strategy = "increment")
	@Column(name = "id_tnm", unique = true, nullable = false)
	public Integer getIdTnm() {
		return this.idTnm;
	}

	public void setIdTnm(Integer idTnm) {
		this.idTnm = idTnm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_phase", nullable = false)
	public ChuPhaseTumeur getChuPhaseTumeur() {
		return this.chuPhaseTumeur;
	}

	public void setChuPhaseTumeur(ChuPhaseTumeur chuPhaseTumeur) {
		this.chuPhaseTumeur = chuPhaseTumeur;
	}

	@Column(name = "t", length = 50)
	public String getT() {
		return this.t;
	}

	public void setT(String t) {
		this.t = t;
	}

	@Column(name = "n", length = 50)
	public String getN() {
		return this.n;
	}

	public void setN(String n) {
		this.n = n;
	}

	@Column(name = "m", length = 50)
	public String getM() {
		return this.m;
	}

	public void setM(String m) {
		this.m = m;
	}

	@Column(name = "type", length = 2)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "taille", length = 50)
	public String getTaille() {
		return this.taille;
	}

	public void setTaille(String taille) {
		this.taille = taille;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idTnm == null) ? 0 : idTnm.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ChuTnm other = (ChuTnm) obj;
		if (idTnm == null) {
			if (other.idTnm != null)
				return false;
		} else if (!idTnm.equals(other.idTnm))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ChuTnm [idTnm=" + idTnm + ", t=" + t + ", n=" + n + ", m=" + m + ", type=" + type + ", taille=" + taille
				+ "]";
	}

}
