package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * ChuTraitement generated by hbm2java
 */
@Entity
@Table(name = "chu_traitement", schema = "db_chu_breast")
public class ChuTraitement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTraitement;
	private ChuMethodeTraitement chuMethodeTraitement;
	private ChuPhaseTumeur chuPhaseTumeur;
	private ChuProtocoleTraitement chuProtocoleTraitement;
	private ChuReponse chuReponse;
	private ChuTypeTraitement chuTypeTraitement;
	private Date dateDebut;
	private Date dateFin;
	private String dose;
	private String nbCures;
	private Boolean ggSentinelle;

	public ChuTraitement() {
	}

	public ChuTraitement(Integer idTraitement, ChuMethodeTraitement chuMethodeTraitement, ChuPhaseTumeur chuPhaseTumeur,
			ChuTypeTraitement chuTypeTraitement) {
		this.idTraitement = idTraitement;
		this.chuMethodeTraitement = chuMethodeTraitement;
		this.chuPhaseTumeur = chuPhaseTumeur;
		this.chuTypeTraitement = chuTypeTraitement;
	}

	public ChuTraitement(Integer idTraitement, ChuMethodeTraitement chuMethodeTraitement, ChuPhaseTumeur chuPhaseTumeur,
			ChuProtocoleTraitement chuProtocoleTraitement, ChuReponse chuReponse, ChuTypeTraitement chuTypeTraitement,
			Date dateDebut, Date dateFin, String dose, String nbCures, Boolean ggSentinelle) {
		this.idTraitement = idTraitement;
		this.chuMethodeTraitement = chuMethodeTraitement;
		this.chuPhaseTumeur = chuPhaseTumeur;
		this.chuProtocoleTraitement = chuProtocoleTraitement;
		this.chuReponse = chuReponse;
		this.chuTypeTraitement = chuTypeTraitement;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.dose = dose;
		this.nbCures = nbCures;
		this.ggSentinelle = ggSentinelle;
	}

	@Id
	@GeneratedValue(generator="increment")
	@GenericGenerator(name="increment", strategy = "increment")
	@Column(name = "id_traitement", unique = true, nullable = false)
	public Integer getIdTraitement() {
		return this.idTraitement;
	}

	public void setIdTraitement(Integer idTraitement) {
		this.idTraitement = idTraitement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_methode", nullable = false)
	public ChuMethodeTraitement getChuMethodeTraitement() {
		return this.chuMethodeTraitement;
	}

	public void setChuMethodeTraitement(ChuMethodeTraitement chuMethodeTraitement) {
		this.chuMethodeTraitement = chuMethodeTraitement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_phase", nullable = false)
	public ChuPhaseTumeur getChuPhaseTumeur() {
		return this.chuPhaseTumeur;
	}

	public void setChuPhaseTumeur(ChuPhaseTumeur chuPhaseTumeur) {
		this.chuPhaseTumeur = chuPhaseTumeur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_protocole")
	public ChuProtocoleTraitement getChuProtocoleTraitement() {
		return this.chuProtocoleTraitement;
	}

	public void setChuProtocoleTraitement(ChuProtocoleTraitement chuProtocoleTraitement) {
		this.chuProtocoleTraitement = chuProtocoleTraitement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_reponse")
	public ChuReponse getChuReponse() {
		return this.chuReponse;
	}

	public void setChuReponse(ChuReponse chuReponse) {
		this.chuReponse = chuReponse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_type_traitement", nullable = false)
	public ChuTypeTraitement getChuTypeTraitement() {
		return this.chuTypeTraitement;
	}

	public void setChuTypeTraitement(ChuTypeTraitement chuTypeTraitement) {
		this.chuTypeTraitement = chuTypeTraitement;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_debut", length = 13)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_fin", length = 13)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Column(name = "dose")
	public String getDose() {
		return this.dose;
	}

	public void setDose(String dose) {
		this.dose = dose;
	}

	@Column(name = "nb_cures")
	public String getNbCures() {
		return this.nbCures;
	}

	public void setNbCures(String nbCures) {
		this.nbCures = nbCures;
	}

	@Column(name = "gg_sentinelle")
	public Boolean getGgSentinelle() {
		return this.ggSentinelle;
	}

	public void setGgSentinelle(Boolean ggSentinelle) {
		this.ggSentinelle = ggSentinelle;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idTraitement == null) ? 0 : idTraitement.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ChuTraitement other = (ChuTraitement) obj;
		if (idTraitement == null) {
			if (other.idTraitement != null)
				return false;
		} else if (!idTraitement.equals(other.idTraitement))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ChuTraitement [idTraitement=" + idTraitement + ", chuProtocoleTraitement=" + chuProtocoleTraitement
				+ ", chuReponse=" + chuReponse + ", chuTypeTraitement=" + chuTypeTraitement + ", dateDebut=" + dateDebut
				+ ", dateFin=" + dateFin + ", dose=" + dose + ", nbCures=" + nbCures + ", ggSentinelle=" + ggSentinelle
				+ "]";
	}

	public boolean dataEmpty() {
		return this.getChuProtocoleTraitement()==null && this.getDateDebut()==null;
	}
}
