package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChuTypePhase generated by hbm2java
 */
@Entity
@Table(name = "chu_type_phase", schema = "db_chu_breast")
public class ChuTypePhase implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTypePhase;
	private String nom;
	private List<ChuPhaseTumeur> chuPhaseTumeurs = new ArrayList<ChuPhaseTumeur>(0);

	public ChuTypePhase() {
	}

	public ChuTypePhase(Integer idTypePhase, String nom) {
		this.idTypePhase = idTypePhase;
		this.nom = nom;
	}

	public ChuTypePhase(Integer idTypePhase, String nom, List<ChuPhaseTumeur> chuPhaseTumeurs) {
		this.idTypePhase = idTypePhase;
		this.nom = nom;
		this.chuPhaseTumeurs = chuPhaseTumeurs;
	}

	@Id

	@Column(name = "id_type_phase", unique = true, nullable = false)
	public Integer getIdTypePhase() {
		return this.idTypePhase;
	}

	public void setIdTypePhase(Integer idTypePhase) {
		this.idTypePhase = idTypePhase;
	}

	@Column(name = "nom", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuTypePhase")
	public List<ChuPhaseTumeur> getChuPhaseTumeurs() {
		return this.chuPhaseTumeurs;
	}

	public void setChuPhaseTumeurs(List<ChuPhaseTumeur> chuPhaseTumeurs) {
		this.chuPhaseTumeurs = chuPhaseTumeurs;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idTypePhase == null) ? 0 : idTypePhase.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ChuTypePhase other = (ChuTypePhase) obj;
		if (idTypePhase == null) {
			if (other.idTypePhase != null)
				return false;
		} else if (!idTypePhase.equals(other.idTypePhase))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ChuTypePhase [idTypePhase=" + idTypePhase + ", nom=" + nom + "]";
	}
	
	

}
