package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChuTopographie generated by hbm2java
 */
@Entity
@Table(name = "chu_topographie", schema = "db_chu_breast")
public class ChuTopographie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idTopographie;
	private ChuGroupeTopographie chuGroupeTopographie;
	private String nomFr;
	private String nomEn;

	public ChuTopographie() {
	}

	public ChuTopographie(String idTopographie) {
		this.idTopographie = idTopographie;
	}

	public ChuTopographie(String idTopographie, ChuGroupeTopographie chuGroupeTopographie, String nomFr, String nomEn) {
		this.idTopographie = idTopographie;
		this.chuGroupeTopographie = chuGroupeTopographie;
		this.nomFr = nomFr;
		this.nomEn = nomEn;
	}

	@Id

	@Column(name = "id_topographie", unique = true, nullable = false, length = 20)
	public String getIdTopographie() {
		return this.idTopographie;
	}

	public void setIdTopographie(String idTopographie) {
		this.idTopographie = idTopographie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_groupe_topo")
	public ChuGroupeTopographie getChuGroupeTopographie() {
		return this.chuGroupeTopographie;
	}

	public void setChuGroupeTopographie(ChuGroupeTopographie chuGroupeTopographie) {
		this.chuGroupeTopographie = chuGroupeTopographie;
	}

	@Column(name = "nom_fr")
	public String getNomFr() {
		return this.nomFr;
	}

	public void setNomFr(String nomFr) {
		this.nomFr = nomFr;
	}

	@Column(name = "nom_en")
	public String getNomEn() {
		return this.nomEn;
	}

	public void setNomEn(String nomEn) {
		this.nomEn = nomEn;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idTopographie == null) ? 0 : idTopographie.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ChuTopographie other = (ChuTopographie) obj;
		if (idTopographie == null) {
			if (other.idTopographie != null)
				return false;
		} else if (!idTopographie.equals(other.idTopographie))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ChuTopographie [idTopographie=" + idTopographie + ", nomFr=" + nomFr + ", nomEn=" + nomEn + "]";
	}

}
