package dbchubreast_web.entity;
// Generated 19 d�c. 2016 13:44:40 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChuTypeAdresse generated by hbm2java
 */
@Entity
@Table(name = "chu_type_adresse", schema = "db_chu_breast")
public class ChuTypeAdresse implements java.io.Serializable {

	private Integer idTypeAdresse;
	private String nom;
	private Set<ChuAdresse> chuAdresses = new HashSet<ChuAdresse>(0);

	public ChuTypeAdresse() {
	}

	public ChuTypeAdresse(Integer idTypeAdresse, String nom) {
		this.idTypeAdresse = idTypeAdresse;
		this.nom = nom;
	}

	public ChuTypeAdresse(Integer idTypeAdresse, String nom, Set<ChuAdresse> chuAdresses) {
		this.idTypeAdresse = idTypeAdresse;
		this.nom = nom;
		this.chuAdresses = chuAdresses;
	}

	@Id

	@Column(name = "id_type_adresse", unique = true, nullable = false)
	public Integer getIdTypeAdresse() {
		return this.idTypeAdresse;
	}

	public void setIdTypeAdresse(Integer idTypeAdresse) {
		this.idTypeAdresse = idTypeAdresse;
	}

	@Column(name = "nom", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuTypeAdresse")
	public Set<ChuAdresse> getChuAdresses() {
		return this.chuAdresses;
	}

	public void setChuAdresses(Set<ChuAdresse> chuAdresses) {
		this.chuAdresses = chuAdresses;
	}

}
